jwt:
  secret: 'secret_code'
  expiresIn: 3600
habitat:
  buildingZones:
    counterForNewHabitat: 10
    isPossibleToCreateNewZones: true
  buildingQueue:
    maxElementsInQueue: 5
    allowMultipleLevelUpdate: true
