database:
  type: 'better-sqlite3'
  host: ''
  port: ''
  username: ''
  password: ''
  database: 'mydb.db'
  synchronize: true
jwt:
  secret: 'secret_code'
  expiresIn: 3600
  ignoreExpiration: false
security:
  headerTokenToLogin: 'secret_header_token'
  whitelistedIp: null
runtime:
  habitat:
    buildingZones:
      counterForNewHabitat: 10
      isPossibleToCreateNewZones: true
    buildingQueue:
      maxElementsInQueue: 5
      allowMultipleLevelUpdate: true
    onStart:
      resources:
        - id: 'wood'
          amount: 30
        - id: 'coal'
          amount: 5
      buildings:
        - id: 'warehouse'
          localBuildingZoneId: 1
          level: 1
        - id: 'university'
          localBuildingZoneId: 2
          level: 1
  mechanics:
    resources:
      calculation: 'no-distance-simple-multiply'
      warehouse: 'base-resource-summary'
